database_type: "postgres"
database: 
username: 
password: 
host: 
port: 
schema: 
table: 
full_load: 
start_date: 
end_date: 
frequency: "
output: 

# database_type: "mongodb"
# database: 
# collection: 
# full_load: 
