database_type: "postgres"
database: "syncsafe"
username: "syncsafe"
password: "AVNS_0WRP9YKcMhQgG-y_MMd"
host: "s2datasystems-do-user-15810817-0.c.db.ondigitalocean.com"
port: "25060"
schema: "Kunika"
table: "basic"
full_load: "True"
start_date: "2024-04-11"
end_date: "2024-04-25"
frequency: "daily"
output: "json"

# database_type: "mongodb"
# database: "Kunika"
# collection: "basic"
# full_load: "False"